---
name: verify

on:
  push:
    branches: [ main ]
  pull_request:
  # required for this workflow to be reusable
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - run: make verify
